#!/usr/bin/env python3

# Créer un quiz de chimie avec des éléments difficiles (pas de correspondance évidente)
chemistry_pairs = [
    ("Sodium", "Na"),
    ("Potassium", "K"), 
    ("Fer", "Fe"),
    ("Cuivre", "Cu"),
    ("Argent", "Ag"),
    ("Or", "Au"),
    ("Plomb", "Pb"),
    ("Étain", "Sn"),
    ("Antimoine", "Sb"),
    ("Tungstène", "W"),
    ("Mercure", "Hg"),
    ("Thallium", "Tl"),
    ("Bismuth", "Bi"),
    ("Uranium", "U"),
    ("Plutonium", "Pu"),
    ("Soufre", "S"),
    ("Chlore", "Cl"),
    ("Argon", "Ar"),
    ("Calcium", "Ca"),
    ("Scandium", "Sc"),
    ("Titane", "Ti"),
    ("Vanadium", "V"),
    ("Chrome", "Cr"),
    ("Manganèse", "Mn"),
    ("Cobalt", "Co"),
    ("Nickel", "Ni"),
    ("Zinc", "Zn"),
    ("Gallium", "Ga"),
    ("Germanium", "Ge"),
    ("Arsenic", "As"),
    ("Sélénium", "Se"),
    ("Brome", "Br"),
    ("Krypton", "Kr"),
    ("Rubidium", "Rb"),
    ("Strontium", "Sr"),
    ("Yttrium", "Y"),
    ("Zirconium", "Zr"),
    ("Niobium", "Nb"),
    ("Molybdène", "Mo"),
    ("Technétium", "Tc"),
    ("Ruthénium", "Ru"),
    ("Rhodium", "Rh"),
    ("Palladium", "Pd"),
    ("Cadmium", "Cd"),
    ("Indium", "In"),
    ("Tellure", "Te"),
    ("Iode", "I"),
    ("Xénon", "Xe"),
    ("Césium", "Cs"),
    ("Baryum", "Ba"),
    ("Lanthane", "La"),
    ("Cérium", "Ce"),
    ("Praséodyme", "Pr"),
    ("Néodyme", "Nd"),
    ("Prométhium", "Pm"),
    ("Samarium", "Sm"),
    ("Europium", "Eu"),
    ("Gadolinium", "Gd"),
    ("Terbium", "Tb"),
    ("Dysprosium", "Dy"),
    ("Holmium", "Ho"),
    ("Erbium", "Er"),
    ("Thulium", "Tm"),
    ("Ytterbium", "Yb"),
    ("Lutécium", "Lu"),
    ("Hafnium", "Hf"),
    ("Tantale", "Ta"),
    ("Rhénium", "Re"),
    ("Osmium", "Os"),
    ("Iridium", "Ir"),
    ("Platine", "Pt"),
    ("Radon", "Rn"),
    ("Francium", "Fr"),
    ("Radium", "Ra"),
    ("Actinium", "Ac"),
    ("Thorium", "Th"),
    ("Protactinium", "Pa"),
    ("Neptunium", "Np"),
    ("Américium", "Am"),
    ("Curium", "Cm"),
    ("Berkélium", "Bk"),
    ("Californium", "Cf"),
    ("Einsteinium", "Es"),
    ("Fermium", "Fm"),
    ("Mendélévium", "Md"),
    ("Nobélium", "No"),
    ("Lawrencium", "Lr"),
    ("Rutherfordium", "Rf"),
    ("Dubnium", "Db"),
    ("Seaborgium", "Sg"),
    ("Bohrium", "Bh"),
    ("Hassium", "Hs"),
    ("Meitnérium", "Mt"),
    ("Darmstadtium", "Ds"),
    ("Roentgenium", "Rg"),
    ("Copernicium", "Cn"),
    ("Nihonium", "Nh"),
    ("Flérovium", "Fl"),
    ("Moscovium", "Mc"),
    ("Livermorium", "Lv"),
    ("Tennesse", "Ts"),
    ("Oganesson", "Og"),
]

print("// Quiz de chimie avec éléments difficiles (pas de correspondance évidente)")
print("pairs: [")
for element, symbol in chemistry_pairs:
    print(f"        QuizPair(col1: '{element}', col2: '{symbol}'),")
print("      ],")

print(f"\n// Total: {len(chemistry_pairs)} éléments")
print("// Tous les éléments ont des symboles non évidents")
