// ignore_for_file: non_constant_identifier_names

/// Dataset des pays avec capitale, continent, codes et infos utiles.
/// Langues en toutes lettres (pas d’abréviations).
/// Format: List<Map<String, String>>
///
/// Champs:
/// - pays
/// - capitale
/// - continent (Afrique, Amérique, Asie, Europe, Océanie)
/// - iso (code ISO 3166-1 alpha-2)
/// - monnaie (code ISO 4217)
/// - langue (principale ou officielles, séparées par " / ")
/// - tel (indicatif international)
///
/// Remarque:
/// - Certaines entités ont plusieurs capitales de fait/de jure.
/// - Les appellations et statuts peuvent varier selon les sources.

final List<Map<String, String>> paysCapitalesContinents = [
  // --- AFRIQUE ---
  {"pays":"Afrique du Sud","capitale":"Pretoria / Le Cap / Bloemfontein","continent":"Afrique","iso":"ZA","monnaie":"ZAR","langue":"afrikaans / anglais / ndebele du Sud / sotho du Nord / sotho du Sud / swati / tsonga / tswana / venda / xhosa / zoulou","tel":"+27"},
  {"pays":"Algérie","capitale":"Alger","continent":"Afrique","iso":"DZ","monnaie":"DZD","langue":"arabe / berbère","tel":"+213"},
  {"pays":"Angola","capitale":"Luanda","continent":"Afrique","iso":"AO","monnaie":"AOA","langue":"portugais","tel":"+244"},
  {"pays":"Bénin","capitale":"Porto-Novo","continent":"Afrique","iso":"BJ","monnaie":"XOF","langue":"français","tel":"+229"},
  {"pays":"Botswana","capitale":"Gaborone","continent":"Afrique","iso":"BW","monnaie":"BWP","langue":"anglais / setswana","tel":"+267"},
  {"pays":"Burkina Faso","capitale":"Ouagadougou","continent":"Afrique","iso":"BF","monnaie":"XOF","langue":"français","tel":"+226"},
  {"pays":"Burundi","capitale":"Gitega","continent":"Afrique","iso":"BI","monnaie":"BIF","langue":"kirundi / français / anglais","tel":"+257"},
  {"pays":"Cameroun","capitale":"Yaoundé","continent":"Afrique","iso":"CM","monnaie":"XAF","langue":"français / anglais","tel":"+237"},
  {"pays":"Cap-Vert","capitale":"Praia","continent":"Afrique","iso":"CV","monnaie":"CVE","langue":"portugais","tel":"+238"},
  {"pays":"Comores","capitale":"Moroni","continent":"Afrique","iso":"KM","monnaie":"KMF","langue":"arabe / comorien / français","tel":"+269"},
  {"pays":"Congo (Brazzaville)","capitale":"Brazzaville","continent":"Afrique","iso":"CG","monnaie":"XAF","langue":"français","tel":"+242"},
  {"pays":"République démocratique du Congo","capitale":"Kinshasa","continent":"Afrique","iso":"CD","monnaie":"CDF","langue":"français","tel":"+243"},
  {"pays":"Côte d’Ivoire","capitale":"Yamoussoukro","continent":"Afrique","iso":"CI","monnaie":"XOF","langue":"français","tel":"+225"},
  {"pays":"Djibouti","capitale":"Djibouti","continent":"Afrique","iso":"DJ","monnaie":"DJF","langue":"arabe / français","tel":"+253"},
  {"pays":"Égypte","capitale":"Le Caire","continent":"Afrique","iso":"EG","monnaie":"EGP","langue":"arabe","tel":"+20"},
  {"pays":"Érythrée","capitale":"Asmara","continent":"Afrique","iso":"ER","monnaie":"ERN","langue":"tigrinya / arabe / anglais","tel":"+291"},
  {"pays":"Eswatini","capitale":"Mbabane / Lobamba","continent":"Afrique","iso":"SZ","monnaie":"SZL","langue":"anglais / swati","tel":"+268"},
  {"pays":"Éthiopie","capitale":"Addis-Abeba","continent":"Afrique","iso":"ET","monnaie":"ETB","langue":"amharique","tel":"+251"},
  {"pays":"Gabon","capitale":"Libreville","continent":"Afrique","iso":"GA","monnaie":"XAF","langue":"français","tel":"+241"},
  {"pays":"Gambie","capitale":"Banjul","continent":"Afrique","iso":"GM","monnaie":"GMD","langue":"anglais","tel":"+220"},
  {"pays":"Ghana","capitale":"Accra","continent":"Afrique","iso":"GH","monnaie":"GHS","langue":"anglais","tel":"+233"},
  {"pays":"Guinée","capitale":"Conakry","continent":"Afrique","iso":"GN","monnaie":"GNF","langue":"français","tel":"+224"},
  {"pays":"Guinée-Bissau","capitale":"Bissau","continent":"Afrique","iso":"GW","monnaie":"XOF","langue":"portugais","tel":"+245"},
  {"pays":"Guinée équatoriale","capitale":"Malabo / Ciudad de la Paz (Oyala)","continent":"Afrique","iso":"GQ","monnaie":"XAF","langue":"espagnol / français / portugais","tel":"+240"},
  {"pays":"Kenya","capitale":"Nairobi","continent":"Afrique","iso":"KE","monnaie":"KES","langue":"anglais / swahili","tel":"+254"},
  {"pays":"Lesotho","capitale":"Maseru","continent":"Afrique","iso":"LS","monnaie":"LSL","langue":"sesotho / anglais","tel":"+266"},
  {"pays":"Libéria","capitale":"Monrovia","continent":"Afrique","iso":"LR","monnaie":"LRD","langue":"anglais","tel":"+231"},
  {"pays":"Libye","capitale":"Tripoli","continent":"Afrique","iso":"LY","monnaie":"LYD","langue":"arabe","tel":"+218"},
  {"pays":"Madagascar","capitale":"Antananarivo","continent":"Afrique","iso":"MG","monnaie":"MGA","langue":"malgache / français","tel":"+261"},
  {"pays":"Malawi","capitale":"Lilongwe","continent":"Afrique","iso":"MW","monnaie":"MWK","langue":"anglais / chichewa","tel":"+265"},
  {"pays":"Mali","capitale":"Bamako","continent":"Afrique","iso":"ML","monnaie":"XOF","langue":"français / bambara","tel":"+223"},
  {"pays":"Maroc","capitale":"Rabat","continent":"Afrique","iso":"MA","monnaie":"MAD","langue":"arabe / berbère","tel":"+212"},
  {"pays":"Maurice","capitale":"Port-Louis","continent":"Afrique","iso":"MU","monnaie":"MUR","langue":"anglais / français / créole mauricien","tel":"+230"},
  {"pays":"Mauritanie","capitale":"Nouakchott","continent":"Afrique","iso":"MR","monnaie":"MRU","langue":"arabe","tel":"+222"},
  {"pays":"Mozambique","capitale":"Maputo","continent":"Afrique","iso":"MZ","monnaie":"MZN","langue":"portugais","tel":"+258"},
  {"pays":"Namibie","capitale":"Windhoek","continent":"Afrique","iso":"NA","monnaie":"NAD","langue":"anglais","tel":"+264"},
  {"pays":"Niger","capitale":"Niamey","continent":"Afrique","iso":"NE","monnaie":"XOF","langue":"français","tel":"+227"},
  {"pays":"Nigeria","capitale":"Abuja","continent":"Afrique","iso":"NG","monnaie":"NGN","langue":"anglais","tel":"+234"},
  {"pays":"Ouganda","capitale":"Kampala","continent":"Afrique","iso":"UG","monnaie":"UGX","langue":"anglais / swahili","tel":"+256"},
  {"pays":"République centrafricaine","capitale":"Bangui","continent":"Afrique","iso":"CF","monnaie":"XAF","langue":"français / sango","tel":"+236"},
  {"pays":"Rwanda","capitale":"Kigali","continent":"Afrique","iso":"RW","monnaie":"RWF","langue":"kinyarwanda / français / anglais / swahili","tel":"+250"},
  {"pays":"Sao Tomé-et-Principe","capitale":"São Tomé","continent":"Afrique","iso":"ST","monnaie":"STN","langue":"portugais","tel":"+239"},
  {"pays":"Sénégal","capitale":"Dakar","continent":"Afrique","iso":"SN","monnaie":"XOF","langue":"français","tel":"+221"},
  {"pays":"Seychelles","capitale":"Victoria","continent":"Afrique","iso":"SC","monnaie":"SCR","langue":"créole seychellois / anglais / français","tel":"+248"},
  {"pays":"Sierra Leone","capitale":"Freetown","continent":"Afrique","iso":"SL","monnaie":"SLE","langue":"anglais","tel":"+232"},
  {"pays":"Somalie","capitale":"Mogadiscio","continent":"Afrique","iso":"SO","monnaie":"SOS","langue":"somali / arabe","tel":"+252"},
  {"pays":"Soudan","capitale":"Khartoum","continent":"Afrique","iso":"SD","monnaie":"SDG","langue":"arabe / anglais","tel":"+249"},
  {"pays":"Soudan du Sud","capitale":"Djouba","continent":"Afrique","iso":"SS","monnaie":"SSP","langue":"anglais","tel":"+211"},
  {"pays":"Tanzanie","capitale":"Dodoma","continent":"Afrique","iso":"TZ","monnaie":"TZS","langue":"swahili / anglais","tel":"+255"},
  {"pays":"Tchad","capitale":"N’Djamena","continent":"Afrique","iso":"TD","monnaie":"XAF","langue":"français / arabe","tel":"+235"},
  {"pays":"Togo","capitale":"Lomé","continent":"Afrique","iso":"TG","monnaie":"XOF","langue":"français","tel":"+228"},
  {"pays":"Tunisie","capitale":"Tunis","continent":"Afrique","iso":"TN","monnaie":"TND","langue":"arabe","tel":"+216"},
  {"pays":"Zambie","capitale":"Lusaka","continent":"Afrique","iso":"ZM","monnaie":"ZMW","langue":"anglais","tel":"+260"},
  {"pays":"Zimbabwe","capitale":"Harare","continent":"Afrique","iso":"ZW","monnaie":"ZWL","langue":"anglais / shona / ndebele","tel":"+263"},

  // --- AMÉRIQUE ---
  {"pays":"Antigua-et-Barbuda","capitale":"Saint John’s","continent":"Amérique","iso":"AG","monnaie":"XCD","langue":"anglais","tel":"+1-268"},
  {"pays":"Argentine","capitale":"Buenos Aires","continent":"Amérique","iso":"AR","monnaie":"ARS","langue":"espagnol","tel":"+54"},
  {"pays":"Bahamas","capitale":"Nassau","continent":"Amérique","iso":"BS","monnaie":"BSD","langue":"anglais","tel":"+1-242"},
  {"pays":"Barbade","capitale":"Bridgetown","continent":"Amérique","iso":"BB","monnaie":"BBD","langue":"anglais","tel":"+1-246"},
  {"pays":"Belize","capitale":"Belmopan","continent":"Amérique","iso":"BZ","monnaie":"BZD","langue":"anglais","tel":"+501"},
  {"pays":"Bolivie","capitale":"Sucre / La Paz","continent":"Amérique","iso":"BO","monnaie":"BOB","langue":"espagnol / quechua / aymara / guarani","tel":"+591"},
  {"pays":"Brésil","capitale":"Brasília","continent":"Amérique","iso":"BR","monnaie":"BRL","langue":"portugais","tel":"+55"},
  {"pays":"Canada","capitale":"Ottawa","continent":"Amérique","iso":"CA","monnaie":"CAD","langue":"anglais / français","tel":"+1"},
  {"pays":"Chili","capitale":"Santiago","continent":"Amérique","iso":"CL","monnaie":"CLP","langue":"espagnol","tel":"+56"},
  {"pays":"Colombie","capitale":"Bogotá","continent":"Amérique","iso":"CO","monnaie":"COP","langue":"espagnol","tel":"+57"},
  {"pays":"Costa Rica","capitale":"San José","continent":"Amérique","iso":"CR","monnaie":"CRC","langue":"espagnol","tel":"+506"},
  {"pays":"Cuba","capitale":"La Havane","continent":"Amérique","iso":"CU","monnaie":"CUP","langue":"espagnol","tel":"+53"},
  {"pays":"Dominique","capitale":"Roseau","continent":"Amérique","iso":"DM","monnaie":"XCD","langue":"anglais","tel":"+1-767"},
  {"pays":"Équateur","capitale":"Quito","continent":"Amérique","iso":"EC","monnaie":"USD","langue":"espagnol / kichwa","tel":"+593"},
  {"pays":"États-Unis","capitale":"Washington D.C.","continent":"Amérique","iso":"US","monnaie":"USD","langue":"anglais","tel":"+1"},
  {"pays":"Grenade","capitale":"Saint George’s","continent":"Amérique","iso":"GD","monnaie":"XCD","langue":"anglais","tel":"+1-473"},
  {"pays":"Guatemala","capitale":"Guatemala","continent":"Amérique","iso":"GT","monnaie":"GTQ","langue":"espagnol","tel":"+502"},
  {"pays":"Guyana","capitale":"Georgetown","continent":"Amérique","iso":"GY","monnaie":"GYD","langue":"anglais","tel":"+592"},
  {"pays":"Haïti","capitale":"Port-au-Prince","continent":"Amérique","iso":"HT","monnaie":"HTG","langue":"français / créole haïtien","tel":"+509"},
  {"pays":"Honduras","capitale":"Tegucigalpa","continent":"Amérique","iso":"HN","monnaie":"HNL","langue":"espagnol","tel":"+504"},
  {"pays":"Jamaïque","capitale":"Kingston","continent":"Amérique","iso":"JM","monnaie":"JMD","langue":"anglais","tel":"+1-876"},
  {"pays":"Mexique","capitale":"Mexico","continent":"Amérique","iso":"MX","monnaie":"MXN","langue":"espagnol","tel":"+52"},
  {"pays":"Nicaragua","capitale":"Managua","continent":"Amérique","iso":"NI","monnaie":"NIO","langue":"espagnol","tel":"+505"},
  {"pays":"Panama","capitale":"Panama","continent":"Amérique","iso":"PA","monnaie":"PAB / USD","langue":"espagnol","tel":"+507"},
  {"pays":"Paraguay","capitale":"Asuncion","continent":"Amérique","iso":"PY","monnaie":"PYG","langue":"espagnol / guarani","tel":"+595"},
  {"pays":"Pérou","capitale":"Lima","continent":"Amérique","iso":"PE","monnaie":"PEN","langue":"espagnol / quechua / aymara","tel":"+51"},
  {"pays":"République dominicaine","capitale":"Saint-Domingue","continent":"Amérique","iso":"DO","monnaie":"DOP","langue":"espagnol","tel":"+1-809"},
  {"pays":"Saint-Kitts-et-Nevis","capitale":"Basseterre","continent":"Amérique","iso":"KN","monnaie":"XCD","langue":"anglais","tel":"+1-869"},
  {"pays":"Sainte-Lucie","capitale":"Castries","continent":"Amérique","iso":"LC","monnaie":"XCD","langue":"anglais","tel":"+1-758"},
  {"pays":"Saint-Vincent-et-les-Grenadines","capitale":"Kingstown","continent":"Amérique","iso":"VC","monnaie":"XCD","langue":"anglais","tel":"+1-784"},
  {"pays":"Salvador","capitale":"San Salvador","continent":"Amérique","iso":"SV","monnaie":"USD / BTC","langue":"espagnol","tel":"+503"},
  {"pays":"Suriname","capitale":"Paramaribo","continent":"Amérique","iso":"SR","monnaie":"SRD","langue":"néerlandais","tel":"+597"},
  {"pays":"Trinité-et-Tobago","capitale":"Port-d’Espagne","continent":"Amérique","iso":"TT","monnaie":"TTD","langue":"anglais","tel":"+1-868"},
  {"pays":"Uruguay","capitale":"Montevideo","continent":"Amérique","iso":"UY","monnaie":"UYU","langue":"espagnol","tel":"+598"},
  {"pays":"Venezuela","capitale":"Caracas","continent":"Amérique","iso":"VE","monnaie":"VES","langue":"espagnol","tel":"+58"},

  // --- ASIE ---
  {"pays":"Afghanistan","capitale":"Kaboul","continent":"Asie","iso":"AF","monnaie":"AFN","langue":"pachto / dari","tel":"+93"},
  {"pays":"Arabie saoudite","capitale":"Riyad","continent":"Asie","iso":"SA","monnaie":"SAR","langue":"arabe","tel":"+966"},
  {"pays":"Arménie","capitale":"Erevan","continent":"Asie","iso":"AM","monnaie":"AMD","langue":"arménien","tel":"+374"},
  {"pays":"Azerbaïdjan","capitale":"Bakou","continent":"Asie","iso":"AZ","monnaie":"AZN","langue":"azéri","tel":"+994"},
  {"pays":"Bahreïn","capitale":"Manama","continent":"Asie","iso":"BH","monnaie":"BHD","langue":"arabe","tel":"+973"},
  {"pays":"Bangladesh","capitale":"Dacca","continent":"Asie","iso":"BD","monnaie":"BDT","langue":"bengali","tel":"+880"},
  {"pays":"Bhoutan","capitale":"Thimphou","continent":"Asie","iso":"BT","monnaie":"BTN","langue":"dzongkha","tel":"+975"},
  {"pays":"Birmanie (Myanmar)","capitale":"Naypyidaw","continent":"Asie","iso":"MM","monnaie":"MMK","langue":"birman","tel":"+95"},
  {"pays":"Brunei","capitale":"Bandar Seri Begawan","continent":"Asie","iso":"BN","monnaie":"BND","langue":"malais","tel":"+673"},
  {"pays":"Cambodge","capitale":"Phnom Penh","continent":"Asie","iso":"KH","monnaie":"KHR","langue":"khmer","tel":"+855"},
  {"pays":"Chine","capitale":"Pékin","continent":"Asie","iso":"CN","monnaie":"CNY","langue":"chinois mandarin","tel":"+86"},
  {"pays":"Corée du Nord","capitale":"Pyongyang","continent":"Asie","iso":"KP","monnaie":"KPW","langue":"coréen","tel":"+850"},
  {"pays":"Corée du Sud","capitale":"Séoul","continent":"Asie","iso":"KR","monnaie":"KRW","langue":"coréen","tel":"+82"},
  {"pays":"Émirats arabes unis","capitale":"Abou Dabi","continent":"Asie","iso":"AE","monnaie":"AED","langue":"arabe","tel":"+971"},
  {"pays":"Géorgie","capitale":"Tbilissi","continent":"Asie","iso":"GE","monnaie":"GEL","langue":"géorgien","tel":"+995"},
  {"pays":"Inde","capitale":"New Delhi","continent":"Asie","iso":"IN","monnaie":"INR","langue":"hindi / anglais","tel":"+91"},
  {"pays":"Indonésie","capitale":"Jakarta","continent":"Asie","iso":"ID","monnaie":"IDR","langue":"indonésien","tel":"+62"},
  {"pays":"Iran","capitale":"Téhéran","continent":"Asie","iso":"IR","monnaie":"IRR","langue":"persan","tel":"+98"},
  {"pays":"Irak","capitale":"Bagdad","continent":"Asie","iso":"IQ","monnaie":"IQD","langue":"arabe / kurde","tel":"+964"},
  {"pays":"Israël","capitale":"Jérusalem","continent":"Asie","iso":"IL","monnaie":"ILS","langue":"hébreu / arabe","tel":"+972"},
  {"pays":"Japon","capitale":"Tokyo","continent":"Asie","iso":"JP","monnaie":"JPY","langue":"japonais","tel":"+81"},
  {"pays":"Jordanie","capitale":"Amman","continent":"Asie","iso":"JO","monnaie":"JOD","langue":"arabe","tel":"+962"},
  {"pays":"Kazakhstan","capitale":"Astana","continent":"Asie","iso":"KZ","monnaie":"KZT","langue":"kazakh / russe","tel":"+7"},
  {"pays":"Kirghizistan","capitale":"Bichkek","continent":"Asie","iso":"KG","monnaie":"KGS","langue":"kirghiz / russe","tel":"+996"},
  {"pays":"Koweït","capitale":"Koweït","continent":"Asie","iso":"KW","monnaie":"KWD","langue":"arabe","tel":"+965"},
  {"pays":"Laos","capitale":"Vientiane","continent":"Asie","iso":"LA","monnaie":"LAK","langue":"lao","tel":"+856"},
  {"pays":"Liban","capitale":"Beyrouth","continent":"Asie","iso":"LB","monnaie":"LBP","langue":"arabe","tel":"+961"},
  {"pays":"Malaisie","capitale":"Kuala Lumpur / Putrajaya","continent":"Asie","iso":"MY","monnaie":"MYR","langue":"malais","tel":"+60"},
  {"pays":"Maldives","capitale":"Malé","continent":"Asie","iso":"MV","monnaie":"MVR","langue":"maldivien (divéhi)","tel":"+960"},
  {"pays":"Mongolie","capitale":"Oulan-Bator","continent":"Asie","iso":"MN","monnaie":"MNT","langue":"mongol","tel":"+976"},
  {"pays":"Népal","capitale":"Katmandou","continent":"Asie","iso":"NP","monnaie":"NPR","langue":"népalais","tel":"+977"},
  {"pays":"Oman","capitale":"Mascate","continent":"Asie","iso":"OM","monnaie":"OMR","langue":"arabe","tel":"+968"},
  {"pays":"Ouzbékistan","capitale":"Tachkent","continent":"Asie","iso":"UZ","monnaie":"UZS","langue":"ouzbek","tel":"+998"},
  {"pays":"Pakistan","capitale":"Islamabad","continent":"Asie","iso":"PK","monnaie":"PKR","langue":"ourdou / anglais","tel":"+92"},
  {"pays":"Palestine","capitale":"Ramallah (administrative)","continent":"Asie","iso":"PS","monnaie":"ILS / JOD / EGP","langue":"arabe","tel":"+970"},
  {"pays":"Philippines","capitale":"Manille","continent":"Asie","iso":"PH","monnaie":"PHP","langue":"filipino / anglais","tel":"+63"},
  {"pays":"Qatar","capitale":"Doha","continent":"Asie","iso":"QA","monnaie":"QAR","langue":"arabe","tel":"+974"},
  {"pays":"Singapour","capitale":"Singapour","continent":"Asie","iso":"SG","monnaie":"SGD","langue":"anglais / malais / mandarin / tamoul","tel":"+65"},
  {"pays":"Sri Lanka","capitale":"Sri Jayawardenepura Kotte","continent":"Asie","iso":"LK","monnaie":"LKR","langue":"cingalais / tamoul","tel":"+94"},
  {"pays":"Syrie","capitale":"Damas","continent":"Asie","iso":"SY","monnaie":"SYP","langue":"arabe","tel":"+963"},
  {"pays":"Tadjikistan","capitale":"Douchanbé","continent":"Asie","iso":"TJ","monnaie":"TJS","langue":"tadjik","tel":"+992"},
  {"pays":"Taïwan","capitale":"Taipei","continent":"Asie","iso":"TW","monnaie":"TWD","langue":"chinois mandarin","tel":"+886"},
  {"pays":"Thaïlande","capitale":"Bangkok","continent":"Asie","iso":"TH","monnaie":"THB","langue":"thaï","tel":"+66"},
  {"pays":"Timor oriental","capitale":"Dili","continent":"Asie","iso":"TL","monnaie":"USD","langue":"tétoum / portugais","tel":"+670"},
  {"pays":"Turkménistan","capitale":"Achgabat","continent":"Asie","iso":"TM","monnaie":"TMT","langue":"turkmène","tel":"+993"},
  {"pays":"Turquie","capitale":"Ankara","continent":"Asie","iso":"TR","monnaie":"TRY","langue":"turc","tel":"+90"},
  {"pays":"Viêt Nam","capitale":"Hanoï","continent":"Asie","iso":"VN","monnaie":"VND","langue":"vietnamien","tel":"+84"},
  {"pays":"Yémen","capitale":"Sanaa","continent":"Asie","iso":"YE","monnaie":"YER","langue":"arabe","tel":"+967"},

  // --- EUROPE ---
  {"pays":"Albanie","capitale":"Tirana","continent":"Europe","iso":"AL","monnaie":"ALL","langue":"albanais","tel":"+355"},
  {"pays":"Allemagne","capitale":"Berlin","continent":"Europe","iso":"DE","monnaie":"EUR","langue":"allemand","tel":"+49"},
  {"pays":"Andorre","capitale":"Andorre-la-Vieille","continent":"Europe","iso":"AD","monnaie":"EUR","langue":"catalan","tel":"+376"},
  {"pays":"Autriche","capitale":"Vienne","continent":"Europe","iso":"AT","monnaie":"EUR","langue":"allemand","tel":"+43"},
  {"pays":"Belgique","capitale":"Bruxelles","continent":"Europe","iso":"BE","monnaie":"EUR","langue":"français / néerlandais / allemand","tel":"+32"},
  {"pays":"Biélorussie","capitale":"Minsk","continent":"Europe","iso":"BY","monnaie":"BYN","langue":"biélorusse / russe","tel":"+375"},
  {"pays":"Bosnie-Herzégovine","capitale":"Sarajevo","continent":"Europe","iso":"BA","monnaie":"BAM","langue":"bosnien / croate / serbe","tel":"+387"},
  {"pays":"Bulgarie","capitale":"Sofia","continent":"Europe","iso":"BG","monnaie":"BGN","langue":"bulgare","tel":"+359"},
  {"pays":"Chypre","capitale":"Nicosie","continent":"Europe","iso":"CY","monnaie":"EUR","langue":"grec / turc","tel":"+357"},
  {"pays":"Croatie","capitale":"Zagreb","continent":"Europe","iso":"HR","monnaie":"EUR","langue":"croate","tel":"+385"},
  {"pays":"Danemark","capitale":"Copenhague","continent":"Europe","iso":"DK","monnaie":"DKK","langue":"danois","tel":"+45"},
  {"pays":"Espagne","capitale":"Madrid","continent":"Europe","iso":"ES","monnaie":"EUR","langue":"espagnol","tel":"+34"},
  {"pays":"Estonie","capitale":"Tallinn","continent":"Europe","iso":"EE","monnaie":"EUR","langue":"estonien","tel":"+372"},
  {"pays":"Finlande","capitale":"Helsinki","continent":"Europe","iso":"FI","monnaie":"EUR","langue":"finnois / suédois","tel":"+358"},
  {"pays":"France","capitale":"Paris","continent":"Europe","iso":"FR","monnaie":"EUR","langue":"français","tel":"+33"},
  {"pays":"Grèce","capitale":"Athènes","continent":"Europe","iso":"GR","monnaie":"EUR","langue":"grec","tel":"+30"},
  {"pays":"Hongrie","capitale":"Budapest","continent":"Europe","iso":"HU","monnaie":"HUF","langue":"hongrois","tel":"+36"},
  {"pays":"Irlande","capitale":"Dublin","continent":"Europe","iso":"IE","monnaie":"EUR","langue":"anglais / irlandais","tel":"+353"},
  {"pays":"Islande","capitale":"Reykjavik","continent":"Europe","iso":"IS","monnaie":"ISK","langue":"islandais","tel":"+354"},
  {"pays":"Italie","capitale":"Rome","continent":"Europe","iso":"IT","monnaie":"EUR","langue":"italien","tel":"+39"},
  {"pays":"Kosovo","capitale":"Pristina","continent":"Europe","iso":"XK","monnaie":"EUR","langue":"albanais / serbe","tel":"+383"},
  {"pays":"Lettonie","capitale":"Riga","continent":"Europe","iso":"LV","monnaie":"EUR","langue":"letton","tel":"+371"},
  {"pays":"Liechtenstein","capitale":"Vaduz","continent":"Europe","iso":"LI","monnaie":"CHF","langue":"allemand","tel":"+423"},
  {"pays":"Lituanie","capitale":"Vilnius","continent":"Europe","iso":"LT","monnaie":"EUR","langue":"lituanien","tel":"+370"},
  {"pays":"Luxembourg","capitale":"Luxembourg","continent":"Europe","iso":"LU","monnaie":"EUR","langue":"luxembourgeois / français / allemand","tel":"+352"},
  {"pays":"Malte","capitale":"La Valette","continent":"Europe","iso":"MT","monnaie":"EUR","langue":"maltais / anglais","tel":"+356"},
  {"pays":"Moldavie","capitale":"Chisinau","continent":"Europe","iso":"MD","monnaie":"MDL","langue":"roumain (moldave)","tel":"+373"},
  {"pays":"Monaco","capitale":"Monaco","continent":"Europe","iso":"MC","monnaie":"EUR","langue":"français","tel":"+377"},
  {"pays":"Monténégro","capitale":"Podgorica","continent":"Europe","iso":"ME","monnaie":"EUR","langue":"monténégrin","tel":"+382"},
  {"pays":"Norvège","capitale":"Oslo","continent":"Europe","iso":"NO","monnaie":"NOK","langue":"norvégien","tel":"+47"},
  {"pays":"Pays-Bas","capitale":"Amsterdam","continent":"Europe","iso":"NL","monnaie":"EUR","langue":"néerlandais","tel":"+31"},
  {"pays":"Pologne","capitale":"Varsovie","continent":"Europe","iso":"PL","monnaie":"PLN","langue":"polonais","tel":"+48"},
  {"pays":"Portugal","capitale":"Lisbonne","continent":"Europe","iso":"PT","monnaie":"EUR","langue":"portugais","tel":"+351"},
  {"pays":"République tchèque","capitale":"Prague","continent":"Europe","iso":"CZ","monnaie":"CZK","langue":"tchèque","tel":"+420"},
  {"pays":"Roumanie","capitale":"Bucarest","continent":"Europe","iso":"RO","monnaie":"RON","langue":"roumain","tel":"+40"},
  {"pays":"Royaume-Uni","capitale":"Londres","continent":"Europe","iso":"GB","monnaie":"GBP","langue":"anglais","tel":"+44"},
  {"pays":"Russie","capitale":"Moscou","continent":"Europe","iso":"RU","monnaie":"RUB","langue":"russe","tel":"+7"},
  {"pays":"Saint-Marin","capitale":"Saint-Marin","continent":"Europe","iso":"SM","monnaie":"EUR","langue":"italien","tel":"+378"},
  {"pays":"Serbie","capitale":"Belgrade","continent":"Europe","iso":"RS","monnaie":"RSD","langue":"serbe","tel":"+381"},
  {"pays":"Slovaquie","capitale":"Bratislava","continent":"Europe","iso":"SK","monnaie":"EUR","langue":"slovaque","tel":"+421"},
  {"pays":"Slovénie","capitale":"Ljubljana","continent":"Europe","iso":"SI","monnaie":"EUR","langue":"slovène","tel":"+386"},
  {"pays":"Suède","capitale":"Stockholm","continent":"Europe","iso":"SE","monnaie":"SEK","langue":"suédois","tel":"+46"},
  {"pays":"Suisse","capitale":"Berne","continent":"Europe","iso":"CH","monnaie":"CHF","langue":"allemand / français / italien / romanche","tel":"+41"},
  {"pays":"Ukraine","capitale":"Kiev","continent":"Europe","iso":"UA","monnaie":"UAH","langue":"ukrainien","tel":"+380"},
  {"pays":"Vatican","capitale":"Cité du Vatican","continent":"Europe","iso":"VA","monnaie":"EUR","langue":"latin / italien","tel":"+379"},

  // --- OCÉANIE ---
  {"pays":"Australie","capitale":"Canberra","continent":"Océanie","iso":"AU","monnaie":"AUD","langue":"anglais","tel":"+61"},
  {"pays":"Fidji","capitale":"Suva","continent":"Océanie","iso":"FJ","monnaie":"FJD","langue":"anglais / fidjien / hindi des Fidji","tel":"+679"},
  {"pays":"Kiribati","capitale":"Tarawa-Sud","continent":"Océanie","iso":"KI","monnaie":"AUD","langue":"gilbertin / anglais","tel":"+686"},
  {"pays":"Îles Marshall","capitale":"Majuro","continent":"Océanie","iso":"MH","monnaie":"USD","langue":"marshallais / anglais","tel":"+692"},
  {"pays":"États fédérés de Micronésie","capitale":"Palikir","continent":"Océanie","iso":"FM","monnaie":"USD","langue":"anglais","tel":"+691"},
  {"pays":"Nauru","capitale":"Yaren (de facto)","continent":"Océanie","iso":"NR","monnaie":"AUD","langue":"nauruan / anglais","tel":"+674"},
  {"pays":"Nouvelle-Zélande","capitale":"Wellington","continent":"Océanie","iso":"NZ","monnaie":"NZD","langue":"anglais / maori / langue des signes néo-zélandaise","tel":"+64"},
  {"pays":"Palaos","capitale":"Ngerulmud","continent":"Océanie","iso":"PW","monnaie":"USD","langue":"paluan / anglais","tel":"+680"},
  {"pays":"Papouasie-Nouvelle-Guinée","capitale":"Port Moresby","continent":"Océanie","iso":"PG","monnaie":"PGK","langue":"tok pisin / hiri motu / anglais","tel":"+675"},
  {"pays":"Îles Salomon","capitale":"Honiara","continent":"Océanie","iso":"SB","monnaie":"SBD","langue":"anglais","tel":"+677"},
  {"pays":"Samoa","capitale":"Apia","continent":"Océanie","iso":"WS","monnaie":"WST","langue":"samoan / anglais","tel":"+685"},
  {"pays":"Tonga","capitale":"Nuku’alofa","continent":"Océanie","iso":"TO","monnaie":"TOP","langue":"tongien / anglais","tel":"+676"},
  {"pays":"Tuvalu","capitale":"Funafuti","continent":"Océanie","iso":"TV","monnaie":"AUD","langue":"tuvaluan / anglais","tel":"+688"},
  {"pays":"Vanuatu","capitale":"Port-Vila","continent":"Océanie","iso":"VU","monnaie":"VUV","langue":"bichelamar / anglais / français","tel":"+678"},
];